### ISSUE TITLE
"Error querying remote server" timeout message

### ISSUE THREAD

**Issue by mcncm** [achlipala/frapapp#1]
This may or may not be a bug. An alert with following error message shows up on the student page, after lingering for a few minutes:

```
Server: Error querying remote server for messages: 500
```
It appears to have no other effect, and doesn't _e.g._ log out the visitor. After clicking the 'Ok' button, You can still navigate to other private pages.

Steps to reproduce:

1. Navigate to `https://frap.csail.mit.edu/Private/student/_`.
2. Wait ~10 minutes.

**Comment by achlipala** [comment]
Thanks for pointing that out.  Similar issues have been pestering us all semester, and I just tried a fix to the server configuration.
