### ISSUE TITLE
Wrong author in forum threads

### ISSUE THREAD

**Issue by samuelgruetter** [achlipala/frapapp#8]
In the global forum, there's a thread `fibonacci invariant [private]`, opened by student A, and it has an answer by student B, but it looks more like an answer by an instructor (and if it's by a student, it means that private threads are not private, so there's an issue in any case).

**Comment by achlipala** [comment]
It was just user error, as explained now in that thread.

**Comment by samuelgruetter** [comment]
I see. 
I should also have reported that the same happened in the thread `PSET 5 [private]`.
